Source: https://github.com/krishnaik06/Advanced-House-Price-Prediction-/blob/master/Feature%20Engineering.ipynb

In [15]:
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
# Imports preprocessing functions
%run ./jlu_preprocessing.ipynb

## Functions

#### Algorithms

In [31]:
def predictPrice(X_train, X_test, Y_train, Y_test):
    #regr = SVR().fit(X_train, Y_train)
    regr = Ridge(alpha=100).fit(X_train, Y_train)
    
    train_pred = regr.predict(X_train)
    test_pred = regr.predict(X_test)
    
    print("Train MSE: ", mean_squared_error(Y_train, train_pred))
    print("Test MSE: ", mean_squared_error(Y_test, test_pred))

## Code

In [3]:
begin = time.time()
original_df = pd.read_csv('used_cars_data.csv')
end = time.time()

print("Time taken: ", end - begin)

C:\Users\Adeel\AppData\Local\Temp\ipykernel_3976\1749011710.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  original_df = pd.read_csv('used_cars_data.csv')

Time taken:  76.0322756767273

In [4]:
# Sample a portion of the rows

begin = time.time()
df = original_df.sample(frac=0.30, replace=False, ignore_index=True)
end = time.time()

print("Time taken: ", end - begin)

print(df.shape)
df.head()

Time taken:  1.4635212421417236
(900012, 66)

,vin,back_legroom,bed,bed_height,bed_length,body_type,cabin,city,city_fuel_economy,combine_fuel_economy,...,transmission,transmission_display,trimId,trim_name,vehicle_damage_category,wheel_system,wheel_system_display,wheelbase,width,year
0,KM8K2CAA3MU602980,34.6 in,NaN,NaN,NaN,SUV / Crossover,NaN,Clive,25.0,NaN,...,A,Automatic,t93938,SEL AWD,NaN,AWD,All-Wheel Drive,102.4 in,70.9 in,2021
1,3FA6P0D90LR223678,38.3 in,NaN,NaN,NaN,Sedan,NaN,Muncy,NaN,NaN,...,A,6-Speed Automatic,t86417,Titanium AWD,NaN,AWD,All-Wheel Drive,112.2 in,83.5 in,2020
2,3G1BE5SM3GS598653,36.1 in,NaN,NaN,NaN,Sedan,NaN,La Porte,30.0,NaN,...,A,6-Speed Automatic,t65940,LT Sedan FWD,NaN,FWD,Front-Wheel Drive,106.3 in,70.5 in,2016
3,2C3CCAEG7GH343219,40.1 in,NaN,NaN,NaN,Sedan,NaN,Ocala,19.0,NaN,...,A,8-Speed Automatic,t59773,C RWD,NaN,RWD,Rear-Wheel Drive,120.2 in,75 in,2016
4,JM3KFACM9L0748334,39.6 in,NaN,NaN,NaN,SUV / Crossover,NaN,Dublin,25.0,NaN,...,A,Automatic,t89618,Touring FWD,NaN,FWD,Front-Wheel Drive,106.2 in,83.3 in,2020

#### Initial cleaning

In [5]:
df = cleanColumnsAndRows(df)

(900006, 50)

#### Process columns with years

In [6]:
df["year"] = processYears(df)
df.head()

,vin,back_legroom,body_type,city,city_fuel_economy,daysonmarket,dealer_zip,description,engine_cylinders,engine_displacement,...,torque,transmission,transmission_display,trimId,trim_name,wheel_system,wheel_system_display,wheelbase,width,year
0,KM8K2CAA3MU602980,34.6 in,SUV / Crossover,Clive,25.0,35,50325,SONIC SILV 2021 Hyundai Kona SEL AWD 6-Speed A...,I4,2000.0,...,"132 lb-ft @ 4,500 RPM",A,Automatic,t93938,SEL AWD,AWD,All-Wheel Drive,102.4 in,70.9 in,71
1,3FA6P0D90LR223678,38.3 in,Sedan,Muncy,NaN,54,17756,2020 Ford Fusion Titanium 20/29 City/Highway M...,I4,2000.0,...,NaN,A,6-Speed Automatic,t86417,Titanium AWD,AWD,All-Wheel Drive,112.2 in,83.5 in,70
2,3G1BE5SM3GS598653,36.1 in,Sedan,La Porte,30.0,5,46350,***APPLY ON LINE AT OR CALL US TODAY AT *****...,I4,1400.0,...,NaN,A,6-Speed Automatic,t65940,LT Sedan FWD,FWD,Front-Wheel Drive,106.3 in,70.5 in,66
3,2C3CCAEG7GH343219,40.1 in,Sedan,Ocala,19.0,62,34471,Certified. 2016 Chrysler 300C Billet Silver Me...,V6,3600.0,...,"394 lb-ft @ 4,200 RPM",A,8-Speed Automatic,t59773,C RWD,RWD,Rear-Wheel Drive,120.2 in,75 in,66
4,JM3KFACM9L0748334,39.6 in,SUV / Crossover,Dublin,25.0,274,94568,Your safety is our Top Priority. We are consta...,I4,2500.0,...,"186 lb-ft @ 4,000 RPM",A,Automatic,t89618,Touring FWD,FWD,Front-Wheel Drive,106.2 in,83.3 in,70

#### Standardize columns of differing data types

In [7]:
df, price_col = convertColumnsToNumericalAndStandardize(df)
df.head()

year

,body_type,city,city_fuel_economy,daysonmarket,engine_cylinders,engine_displacement,engine_type,exterior_color,franchise_dealer,franchise_make,...,model_name,savings_amount,seller_rating,sp_name,transmission,transmission_display,trim_name,wheel_system,wheel_system_display,year
0,0.078789,-1.126246,2.857666e-01,-0.377576,-0.841462,-0.738847,-0.841462,1.119713,0.484306,-0.502081,...,0.030949,-0.510943,0.161731,1.287006,-0.390506,0.623558,0.494563,-0.194711,-1.184887,0.787856
1,0.864471,0.346014,8.819081e-16,-0.203031,-0.841462,-0.738847,-0.841462,-0.242331,0.484306,-0.825810,...,-0.341247,-0.510943,0.204950,0.556939,-0.390506,-1.583002,1.016059,-0.194711,-1.184887,0.547083
2,0.864471,-0.132163,9.063542e-01,-0.653173,-0.841462,-1.197695,-0.841462,0.846818,-2.064810,1.375546,...,-0.776919,1.578548,1.429483,-1.668672,-0.390506,-1.583002,-0.133892,0.537910,0.528938,-0.416008
3,0.864471,0.541596,-4.589386e-01,-0.129538,0.753576,0.484747,0.753576,-1.392688,0.484306,-1.084793,...,-1.682885,-0.318881,-0.312075,0.786469,-0.390506,-0.234549,-0.940444,1.270531,1.385851,-0.416008
4,0.078789,-0.900633,2.857666e-01,1.818017,-0.841462,-0.356474,-0.841462,1.109770,0.484306,0.274868,...,-1.051017,-0.510943,-0.203228,-0.692005,-0.390506,0.623558,1.025271,0.537910,0.528938,0.547083

#### Run algorithm

In [8]:
# X_train, X_test, Y_train, Y_test = train_test_split(df.to_numpy(), price_col.to_numpy(), test_size=0.2)

# predictPrice(X_train, X_test, Y_train, Y_test)

#LinReg Result

In [ ]:
# X_train, X_test, Y_train, Y_test = train_test_split(df.to_numpy(), price_col.to_numpy(), test_size=0.2)

# predictPrice(X_train, X_test, Y_train, Y_test)

# #SVR Result

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(df.to_numpy(), price_col.to_numpy(), test_size=0.2)

In [38]:
# param_grid = {'alpha':[1.5,2,2.5,3,3.5,4,10,20,30,40,50,100], 'solver':['auto', 'svd']}

In [39]:
grid =  GridSearchCV(predictPrice(X_train, X_test, Y_train, Y_test), param_grid)

Train MSE:  200748072.93707803
Test MSE:  161673066.64892998

In [35]:
# grid.fit(X_train, Y_train)

In [40]:
# print(grid.best_params_)
# grid_predictions = grid.predict(X_test)

In [32]:
predictPrice(X_train, X_test, Y_train, Y_test)

Train MSE:  200748072.93707803
Test MSE:  161673066.64892998